# Generated by Django 3.1.7 on 2021-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='itempic/'),
        ),
    ]
